app = 'l3chat'
primary_region = 'lax'

[build]
dockerfile = "Dockerfile"

[env]
LEPTOS_OUTPUT_NAME="l3chat"
LEPTOS_SITE_ROOT="site"
LEPTOS_SITE_PKG_DIR = "pkg"
LEPTOS_SITE_ADDR="0.0.0.0:8080"
PORT = "8080"
RUST_LOG="info"

[http_service]
internal_port = 8080
force_https = true
auto_stop_machines = true
auto_start_machines = true
min_machines_running = 1
processes = ['app']

[[vm]]
memory = '1gb'
cpu_kind = 'shared'
cpus = 1
memory_mb = 1024
